const $ = (selector, parent=document) => parent.querySelector(selector);
const $$ = (selector, parent=document) => [...parent.querySelectorAll(selector)];
const menu = $('.menu-toggle');
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Закрыть меню':'Открыть меню');$('.header nav').classList.toggle('open',open)});
$$('.header nav a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Открыть меню');$('.header nav').classList.remove('open')}));

const courses = {
 rf: { title:'Основы СВЧ-измерений', subtitle:'Ключевые направления СВЧ-измерений — от базовых принципов до работы с приборами.', image:'course-rf', badge:'БАЗОВЫЙ КУРС', level:'Базовый', format:'Онлайн + очно', duration:'1 месяц', price:'50 000 ₽', unit:'за одного участника', audience:['student','specialist','company'], description:'Системное понимание СВЧ-техники, методов измерений и уверенная работа с современным радиоизмерительным оборудованием.', content:`<div class="detail-section"><h3>Два модуля. Теория и практика.</h3><details open><summary>Модуль 1 — основа инженерных измерений</summary><p>9 технических онлайн-уроков, 2 лабораторные работы, решение первого кейса, тестирование и игра «Плацдарм РЭП».</p><ul><li>Основы СВЧ и метрологии</li><li>Базовые измерительные приборы и осциллография</li><li>Измерители мощности и генерация сигналов</li><li>Анализаторы спектра, цифровая модуляция</li><li>Векторный анализ цепей</li></ul></details><details><summary>Модуль 2 — специализированные измерения</summary><p>11 технических онлайн-уроков, 2 лабораторные работы, решение второго кейса и тестирование.</p><ul><li>Анализ импеданса и параметрические измерения</li><li>Измерение параметров материалов, зондовые станции</li><li>Load-Pull измерения и САПР</li><li>Решения для телекоммуникаций</li><li>Испытательное оборудование и испытания на ЭМС</li><li>Измерения радиофотонных устройств и квантовые измерения</li></ul></details></div><div class="detail-section"><h3>Лабораторные работы</h3><p>Основы осциллографии, генерация сигналов, анализ спектра, векторный анализ сигналов с цифровой модуляцией и векторный анализ цепей. Специализированные направления включают автоматизацию измерений и зондовые измерения.</p></div><div class="detail-section"><h3>Бонус: гибкие навыки</h3><p>Постановка целей, аргументация, работа в команде, тайм-менеджмент и стрессоустойчивость.</p></div><p class="detail-note">Для студентов — скидка 50% или грант на конкурсной основе. Условия и наличие мест уточняются при записи. По завершении курса — сертификат о дополнительном образовании.</p>` },
 telecom: { title:'Современные системы сотовой связи', subtitle:'Курс «Телеком 5G»: измерения и тестирование телекоммуникационных систем.', image:'course-5g', badge:'ТЕЛЕКОМ 5G', level:'Продвинутый', format:'Онлайн + очно', duration:'По программе', price:'110 000 ₽', unit:'за одного участника', audience:['student','specialist','company'], description:'Развивайте компетенции в измерениях и тестировании современных телекоммуникационных систем.', content:`<div class="detail-section"><h3>Для кого эта программа</h3><p>Для студентов технических направлений, инженеров и специалистов, которым необходимо развить компетенции в современных системах сотовой связи.</p></div><div class="detail-section"><h3>Фокус обучения</h3><ul><li>Измерения в телекоммуникационных системах</li><li>Тестирование систем сотовой связи</li><li>Применение знаний в практических инженерных задачах</li></ul></div><p class="detail-note">Точное содержание, требования к подготовке и расписание предоставляет команда Академии при подборе программы.</p>` },
 corporate: { title:'Корпоративный курс', subtitle:'Программа под ваши задачи, оборудование и уровень подготовки команды.', image:'course-team', badge:'ДЛЯ КОМАНД', level:'По запросу', format:'По запросу', duration:'Индивидуально', price:'от 70 000 ₽', unit:'условия по запросу', audience:['company'], description:'Обучение сотрудников с учётом задач компании: от освоения новых приборов до согласованного подхода к измерениям.', content:`<div class="detail-section"><h3>Кому подойдёт</h3><ul><li>Инженерам и специалистам по измерениям</li><li>Разработчикам и сотрудникам R&D</li><li>Руководителям лабораторий и технических подразделений</li><li>Проектным командам и молодым специалистам</li></ul></div><div class="detail-section"><h3>Как формируется программа</h3><p>Учитываем оборудование, техническое направление, задачи заказчика и подготовку сотрудников. Совмещаем практические инженерные задачи с отработкой аргументации и защиты результатов.</p></div><div class="detail-section"><h3>Практический результат</h3><p>Команда получает общую базу для подготовки, проведения и анализа измерений. Обучение помогает освоить оборудование и начать работу в новом техническом направлении.</p></div><p class="detail-note">Содержание, длительность, формат и итоговая стоимость определяются после обсуждения задачи. Игра «Плацдарм РЭП» может дополнять корпоративный курс.</p>` },
 game: { title:'Игра «Плацдарм РЭП»', subtitle:'Командная практика принятия и защиты инженерных решений.', image:'course-game', badge:'ИНЖЕНЕРНАЯ ИГРА', level:'От 15 человек', format:'Очно', duration:'По согласованию', price:'от 300 000 ₽', unit:'за мероприятие', audience:['company'], description:'Отдельный образовательный продукт или дополнение к корпоративному курсу для команды от 15 человек.', content:`<div class="detail-section"><h3>Опыт, который объединяет</h3><p>Игра позволяет отрабатывать аргументацию, командное взаимодействие и защиту полученных результатов на основе технических решений.</p></div><div class="detail-section"><h3>Формат участия</h3><ul><li>Очное командное мероприятие</li><li>Группа от 15 участников</li><li>Самостоятельный формат или часть корпоративного курса</li></ul></div><img class="media-full" src="assets/game.webp" alt="Участники игры Плацдарм РЭП"><p class="detail-note">Сценарий, длительность, площадка и окончательная стоимость согласуются с командой Академии.</p>` }
};

function renderCourses(filter='all') {
 const selected=Object.entries(courses).filter(([,c])=>filter==='all'||c.audience.includes(filter));
 $('#program-grid').innerHTML=selected.map(([key,c])=>`<article class="program-card"><div class="program-art"><img src="assets/${c.image}.webp" alt="" loading="lazy"><span class="course-badge">${c.badge}</span></div><div class="program-info"><h3><button class="course-detail-link" data-course="${key}">${c.title}</button></h3><p>${c.subtitle}</p><div class="program-meta"><span>${c.level}</span><span>${c.format}</span></div><div class="program-bottom"><div class="program-price"><small>${c.unit}</small><strong>${c.price}</strong></div><button class="program-open" data-course="${key}" aria-label="Подробнее: ${c.title.replaceAll('"','&quot;')}">↗</button></div></div></article>`).join('');
 $('.catalog-count').textContent=`${selected.length} программы`;
 $$('.filter').forEach(b=>{const active=b.dataset.filter===filter;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});
}
renderCourses();
$$('.filter').forEach(b=>b.addEventListener('click',()=>renderCourses(b.dataset.filter)));
$$('.audience-pick').forEach(b=>b.addEventListener('click',()=>{renderCourses(b.dataset.filter);$('#programs').scrollIntoView({behavior:reducedMotion()?'instant':'smooth'});$('.filter.active').focus({preventScroll:true})}));

const courseDialog=$('#course-dialog'), mediaDialog=$('#media-dialog');
function openDialog(dialog){dialog.showModal();document.body.style.overflow='hidden'}
function closeDialog(dialog){dialog.close();document.body.style.overflow=''}
$$('dialog').forEach(dialog=>{dialog.addEventListener('close',()=>document.body.style.overflow='');$('.dialog-close',dialog).addEventListener('click',()=>closeDialog(dialog));dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog(dialog)}})});
document.addEventListener('click',event=>{
 const courseButton=event.target.closest('[data-course]');
 if(courseButton){const key=courseButton.dataset.course,c=courses[key];if(!c)return;
 $('#course-detail').innerHTML=`<div class="course-modal-top"><div><div class="section-num">${c.badge}</div><h2 id="course-title">${c.title}</h2><p>${c.description}</p></div><img src="assets/${c.image}.webp" alt=""></div><div class="course-modal-body"><div class="detail-meta"><div><span>Уровень</span><strong>${c.level}</strong></div><div><span>Формат</span><strong>${c.format}</strong></div><div><span>Длительность</span><strong>${c.duration}</strong></div></div>${c.content}</div><div class="course-modal-bottom"><div><strong>${c.price}</strong><small>${c.unit}</small></div><button class="button orange" data-enquire="${key}">Обсудить обучение <span>↗</span></button></div>`;
 courseDialog.setAttribute('aria-labelledby','course-title');openDialog(courseDialog);courseDialog.scrollTop=0;}
 const enquire=event.target.closest('[data-enquire]');
 if(enquire){event.preventDefault();if(courseDialog.open)closeDialog(courseDialog);$('#form-program').value=enquire.dataset.enquire;const company=['corporate','game'].includes(enquire.dataset.enquire);$(`input[name="type"][value="${company?'company':'personal'}"]`).checked=true;setPersonType(company);$('#contact').scrollIntoView({behavior:reducedMotion()?'instant':'smooth'});$('input[name="name"]').focus({preventScroll:true});}
});

const benefits=[{image:'engineer',alt:'Работа с измерительным прибором в лаборатории',caption:'Освоить. Настроить. Измерить.'},{image:'laboratory',alt:'Обучение в лаборатории Академии',caption:'Реальная задача — ваше решение.'},{image:'graduates',alt:'Участники обучения в Академии',caption:'Учиться и продолжать работать.'},{image:'team',alt:'Инженерная команда Акметрон',caption:'Общая цель. Сильная команда.'}];
function chooseBenefit(index,focus=false){const b=benefits[index];$$('[data-benefit]').forEach((button,i)=>{const active=i===index;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;$('.benefit-plus',button).textContent=active?'−':'+';if(active&&focus)button.focus()});$('#benefit-image').src=`assets/${b.image}.webp`;$('#benefit-image').alt=b.alt;$('#benefit-caption').textContent=b.caption;$('#benefit-count').textContent=`0${index+1} / 04`;$('#benefit-panel').setAttribute('aria-labelledby',`benefit-${index}`)}
$$('[data-benefit]').forEach((b,i)=>{b.addEventListener('click',()=>chooseBenefit(i));b.addEventListener('keydown',e=>{let target;if(e.key==='ArrowDown')target=(i+1)%4;if(e.key==='ArrowUp')target=(i+3)%4;if(e.key==='Home')target=0;if(e.key==='End')target=3;if(target!==undefined){e.preventDefault();chooseBenefit(target,true)}})});

const gallery=[{image:'laboratory',title:'В собственной лаборатории',caption:'Практические занятия с измерительными приборами. Фотография из материалов Академии.'},{image:'team',title:'Учиться у практиков',caption:'Инженерная команда Акметрон за работой с оборудованием.'},{image:'game',title:'Игра «Плацдарм РЭП»',caption:'Обсуждение и защита технических решений в команде.'}];let galleryIndex=0;
function showGallery(index){galleryIndex=(index+gallery.length)%gallery.length;const item=gallery[galleryIndex];$('#media-detail').innerHTML=`<h2 id="media-title">${item.title}</h2><img class="media-full" src="assets/${item.image}.webp" alt="${item.title}"><p class="media-caption">${item.caption}</p><div class="gallery-controls"><button data-gallery-prev aria-label="Предыдущее фото">←</button><span>${galleryIndex+1} / ${gallery.length}</span><button data-gallery-next aria-label="Следующее фото">→</button></div>`;mediaDialog.setAttribute('aria-labelledby','media-title');if(!mediaDialog.open)openDialog(mediaDialog)}
$$('[data-gallery]').forEach(b=>b.addEventListener('click',()=>showGallery(Number(b.dataset.gallery))));
mediaDialog.addEventListener('click',e=>{if(e.target.closest('[data-gallery-prev]'))showGallery(galleryIndex-1);if(e.target.closest('[data-gallery-next]'))showGallery(galleryIndex+1)});
mediaDialog.addEventListener('keydown',e=>{if(!$('.gallery-controls',mediaDialog))return;if(e.key==='ArrowRight'){e.preventDefault();showGallery(galleryIndex+1)}if(e.key==='ArrowLeft'){e.preventDefault();showGallery(galleryIndex-1)}});
$$('[data-document]').forEach(b=>b.addEventListener('click',()=>{const license=b.dataset.document==='license';$('#media-detail').innerHTML=license?`<h2 id="media-title">Лицензия Академии</h2><div class="license-full"><img src="assets/license-1.webp" alt="Лицензия, страница 1"><img src="assets/license-2.webp" alt="Лицензия, страница 2"></div><p class="media-caption">№ Л035-01298-77/05108524. Из презентации Академии.</p>`:`<h2 id="media-title">Сертификат выпускника</h2><img class="media-full" src="assets/certificate.webp" alt="Образец сертификата о дополнительном образовании"><p class="media-caption">Образец сертификата из презентации Академии Акметрон.</p>`;mediaDialog.setAttribute('aria-labelledby','media-title');openDialog(mediaDialog);mediaDialog.scrollTop=0}));

function setPersonType(company){$('.company-field').hidden=!company;$('input[name="company"]').required=company}
$$('input[name="type"]').forEach(radio=>radio.addEventListener('change',()=>setPersonType(radio.value==='company')));
const form=$('#enquiry-form');
form.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;$('#form-result').hidden=false;$$('#enquiry-form > :not(#form-result)').forEach(e=>e.inert=true);$('#form-result a').focus({preventScroll:true})});
$('.reset-form').addEventListener('click',()=>{$('#form-result').hidden=true;$$('#enquiry-form > :not(#form-result)').forEach(e=>e.inert=false);form.reset();setPersonType(false);$('input[name="name"]').focus({preventScroll:true})});
function reducedMotion(){return window.matchMedia('(prefers-reduced-motion: reduce)').matches}
if(!reducedMotion()&&'IntersectionObserver'in window){document.documentElement.classList.add('motion');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target)}}),{threshold:.07,rootMargin:'0px 0px 30px 0px'});$$('.reveal').forEach((el)=>observer.observe(el))}
let scrollQueued=false;window.addEventListener('scroll',()=>{if(scrollQueued)return;scrollQueued=true;requestAnimationFrame(()=>{const range=document.documentElement.scrollHeight-window.innerHeight;$('.scroll-progress').style.width=`${range>0?100*window.scrollY/range:0}%`;scrollQueued=false})},{passive:true});
